library:
  source-dirs: src
tests:
  notionfy-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notionfy
copyright: 2019 Yannick
maintainer: https://www.dev-log.me
dependencies:
- either
- parsec
- transformers
- random
- containers
- text
- uuid
- unordered-containers
- bytestring
- http-client
- time
- lens
- lens-aeson
- aeson
- filepath
- extra
- split
- mtl
- wreq
- optparse-applicative
- hspec
- base >= 4.7 && < 5
name: notionfy
version: 0.1.1
extra-source-files:
- README.md
- ChangeLog.md
author: Yannick
github: yannick-cw/notionfy
license: BSD3
executables:
  notionfy-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notionfy
description: Please see the README on GitHub at <https://github.com/githubuser/notionfy#readme>
